/* =========================================================================
   Fisiologia Vegetal — banco de exercícios
   -------------------------------------------------------------------------
   Cada módulo tem um banco; a cada tentativa o site sorteia 6 questões.
   Para adicionar questões, copie um bloco e ajuste. Campos:
     id  -> identificador único
     t   -> tipo: "mc" (múltipla escolha) ou "vf" (verdadeiro/falso)
     q   -> enunciado (pode conter HTML simples: <sub> <sup> <em> <strong>)
     o   -> alternativas: [ ["texto", correta?], ... ]  (mc: 1 correta; vf: já vem pronto)
     fb  -> explicação mostrada após responder
   O identificador do módulo (chave do objeto) segue os nomes dos arquivos:
   01-agua, 02-estomatos, 03-nutricao, 04-floema, 05-fotossintese,
   06-respiracao, 07-hormonios, 08-luz, 09-tropismos, 10-estresse
   ========================================================================= */

window.EXERCICIOS_CONFIG = {
  sortear: 6,                 // quantas questões por tentativa
  aprovacao: 0.7             // fração de acertos para marcar o módulo como concluído
};

/* dica de leitura por módulo, usada no card de livro ao fim do quiz */
window.EXERCICIOS_CAP = {
  "01-agua": "os capítulos 3 e 4 (relações hídricas e transporte no xilema)",
  "02-estomatos": "os capítulos 4 e 10 (transpiração e regulação estomática)",
  "03-nutricao": "os capítulos 5 e 6 (nutrição mineral e absorção de solutos)",
  "04-floema": "o capítulo 11 (translocação no floema)",
  "05-fotossintese": "os capítulos 7 e 8 (fotossíntese: luz e carbono)",
  "06-respiracao": "o capítulo 12 (respiração e metabolismo de lipídios)",
  "07-hormonios": "os capítulos 15 a 19 (hormônios e sinalização)",
  "08-luz": "os capítulos 16 e 20 (fotorreceptores e floração)",
  "09-tropismos": "os capítulos 18 e 20 (auxina e movimentos)",
  "10-estresse": "o capítulo 24 (estresse abiótico)"
};

window.EXERCICIOS = {

  "01-agua": [
    { id: "01-1", t: "mc", q: "Uma célula com Ψ<sub>s</sub> = −0,9 MPa e Ψ<sub>p</sub> = +0,3 MPa é colocada numa solução com Ψ<sub>w</sub> = −0,4 MPa. O que ocorre?",
      o: [["A célula perde água para a solução.", true], ["A célula absorve água e incha.", false], ["Não há fluxo líquido de água.", false], ["A parede celular se rompe.", false]],
      fb: "Ψ<sub>w</sub> da célula = −0,9 + 0,3 = −0,6 MPa. Como −0,6 < −0,4, a água sai da célula (do maior para o menor potencial)." },
    { id: "01-2", t: "mc", q: "Ao meio-dia de um dia quente e seco, em relação ao início da manhã, espera-se que o potencial hídrico da folha e a tensão no xilema:",
      o: [["Ψ da folha mais negativo e tensão maior.", true], ["Ψ da folha mais positivo e tensão menor.", false], ["ambos inalterados: o solo tampona o sistema.", false], ["Ψ da folha positivo e tensão nula.", false]],
      fb: "Maior demanda evaporativa exige gradiente maior: o Ψ da folha cai e a pressão negativa (tensão) no xilema aumenta." },
    { id: "01-3", t: "mc", q: "Qual estrutura obriga a água a cruzar uma membrana antes de entrar no cilindro vascular da raiz?",
      o: [["A estria de Caspary na endoderme.", true], ["A parede primária da epiderme.", false], ["Os plasmodesmos do córtex.", false], ["A cutícula da raiz.", false]],
      fb: "A suberina da estria de Caspary veda o apoplasto nas paredes radiais da endoderme, forçando a rota simplástica/transmembrana." },
    { id: "01-4", t: "mc", q: "Por convenção, a água pura livre, à pressão atmosférica e na altura de referência, tem potencial hídrico igual a:",
      o: [["0 MPa", true], ["−0,03 MPa", false], ["+1 MPa", false], ["−1,5 MPa", false]],
      fb: "Ψ<sub>w</sub> = 0 é o estado de referência. Solutos e tensões tornam Ψ<sub>w</sub> negativo; pressão positiva o aumenta." },
    { id: "01-5", t: "vf", q: "O potencial de soluto (Ψ<sub>s</sub>) de uma solução é sempre menor ou igual a zero.",
      o: [["Verdadeiro", true], ["Falso", false]],
      fb: "Solutos sempre reduzem o potencial hídrico da água; Ψ<sub>s</sub> ≤ 0, tanto mais negativo quanto maior a concentração." },
    { id: "01-6", t: "mc", q: "No topo de uma árvore de 30 m, quanto o componente gravitacional (Ψ<sub>g</sub>) contribui para o potencial hídrico?",
      o: [["cerca de −0,3 MPa", true], ["cerca de +0,3 MPa", false], ["cerca de −3 MPa", false], ["é desprezível em qualquer altura", false]],
      fb: "Ψ<sub>g</sub> ≈ −0,01 MPa por metro. A 30 m: ≈ −0,3 MPa — relevante só em árvores altas." },
    { id: "01-7", t: "mc", q: "O maior salto de potencial hídrico ao longo do contínuo solo–planta–atmosfera ocorre:",
      o: [["na interface folha–ar", true], ["entre o solo e a raiz", false], ["ao longo do xilema do caule", false], ["entre o córtex e a endoderme", false]],
      fb: "O ar, mesmo a 60% de UR, tem Ψ ≈ −70 MPa, contra ≈ −1,5 MPa na folha. É esse degrau que puxa toda a coluna de água." },
    { id: "01-8", t: "mc", q: "A gutação (gotas nas margens das folhas de manhã) é causada principalmente por:",
      o: [["pressão de raiz: bombeamento de íons para o xilema à noite", true], ["condensação do orvalho sobre a folha", false], ["transpiração intensa pelos estômatos", false], ["ruptura de vasos do xilema", false]],
      fb: "Com transpiração mínima, a raiz continua bombeando íons ao xilema; a água entra por osmose e gera pressão positiva que força a seiva pelos hidatódios." },
    { id: "01-9", t: "vf", q: "A ascensão da seiva em árvores altas é explicada principalmente pela pressão de raiz.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "A pressão de raiz (~0,1–0,2 MPa) não sustenta colunas altas. A ascensão é explicada pela teoria da coesão-tensão, movida pela transpiração." },
    { id: "01-10", t: "mc", q: "A cavitação (embolia) de um vaso do xilema ocorre quando:",
      o: [["a tensão excede um limiar e forma-se uma bolha de vapor que rompe a coluna de água", true], ["o potencial de pressão do xilema fica muito positivo", false], ["a raiz absorve água em excesso", false], ["a umidade do ar chega a 100%", false]],
      fb: "Sob tensão excessiva ou congelamento, forma-se uma bolha que interrompe a condução naquele vaso. O fechamento estomático limita o risco." },
    { id: "01-11", t: "mc", q: "As aquaporinas da membrana plasmática:",
      o: [["facilitam a passagem de água pela rota transmembrana, sem gastar energia", true], ["bombeiam água contra o gradiente de potencial", false], ["transportam apenas íons, não água", false], ["só existem nas células-guarda", false]],
      fb: "São canais que aumentam a condutividade hidráulica da membrana; a água ainda se move a favor do gradiente de Ψ<sub>w</sub>." },
    { id: "01-12", t: "vf", q: "A água move-se espontaneamente do ponto de maior para o de menor potencial hídrico.",
      o: [["Verdadeiro", true], ["Falso", false]],
      fb: "Essa é a regra que governa todo o transporte de água na planta, do solo à atmosfera." },
    { id: "01-13", t: "mc", q: "A plasmólise ocorre quando a célula vegetal é colocada em solução:",
      o: [["hipertônica (Ψ<sub>w</sub> menor que o da célula)", true], ["hipotônica (Ψ<sub>w</sub> maior que o da célula)", false], ["isotônica", false], ["de água destilada", false]],
      fb: "Em meio hipertônico a célula perde água, o protoplasto retrai-se e descola da parede — plasmólise." }
  ],

  "02-estomatos": [
    { id: "02-1", t: "mc", q: "Ao amanhecer os estômatos começam a abrir antes de a fotossíntese consumir CO<sub>2</sub> de forma significativa. Qual sinal explica melhor essa abertura precoce?",
      o: [["A luz azul percebida pela fototropina, que ativa a H<sup>+</sup>-ATPase.", true], ["A queda imediata do C<sub>i</sub> pela fixação de carbono.", false], ["O aumento do ABA foliar durante a noite.", false], ["A elevação da temperatura da folha.", false]],
      fb: "A resposta à luz azul é rápida e independe da fotossíntese: fototropina → fosforilação da H<sup>+</sup>-ATPase → hiperpolarização → entrada de K<sup>+</sup>." },
    { id: "02-2", t: "mc", q: "Uma planta bem irrigada passa a um ar muito seco (DPV alto). Depois do transiente, observa-se:",
      o: [["g<sub>s</sub> diminui parcialmente; E sobe menos do que subiria com g<sub>s</sub> constante.", true], ["g<sub>s</sub> aumenta e E aumenta proporcionalmente.", false], ["g<sub>s</sub> e E não mudam, pois só o ABA controla o estômato.", false], ["os estômatos abrem totalmente para resfriar a folha.", false]],
      fb: "O fechamento parcial induzido por DPV limita o pico de transpiração e protege a coluna de água do xilema." },
    { id: "02-3", t: "mc", q: "Por que a razão A/E costuma ser maior com abertura estomática parcial do que com abertura máxima?",
      o: [["A assimilação satura com g<sub>s</sub>, mas a transpiração continua crescendo quase linearmente.", true], ["A transpiração satura antes da assimilação.", false], ["Com o poro parcialmente aberto não há difusão de CO<sub>2</sub>.", false], ["A abertura máxima fecha a difusão de vapor.", false]],
      fb: "Como A tende a um platô (luz e bioquímica) enquanto E cresce com o gradiente de vapor, o ganho marginal de carbono por unidade de água cai." },
    { id: "02-4", t: "mc", q: "Qual íon entra nas células-guarda impulsionando a abertura do poro?",
      o: [["K<sup>+</sup>", true], ["Ca<sup>2+</sup>", false], ["Na<sup>+</sup>", false], ["Mg<sup>2+</sup>", false]],
      fb: "A hiperpolarização abre canais de entrada de K<sup>+</sup> (KAT1); o K<sup>+</sup> entra, baixa o Ψ<sub>s</sub>, a água entra e o turgor sobe." },
    { id: "02-5", t: "mc", q: "Que espécies funcionam como contra-íons do K<sup>+</sup> durante a abertura estomática?",
      o: [["Cl<sup>−</sup> e malato<sup>2−</sup>", true], ["NO<sub>3</sub><sup>−</sup> e SO<sub>4</sub><sup>2−</sup>", false], ["HCO<sub>3</sub><sup>−</sup> e H<sup>+</sup>", false], ["apenas água", false]],
      fb: "O Cl<sup>−</sup> entra e o malato<sup>2−</sup> é produzido a partir do amido, equilibrando a carga do K<sup>+</sup> acumulado." },
    { id: "02-6", t: "mc", q: "O espessamento diferencial da parede das células-guarda é maior:",
      o: [["na parede interna, voltada para o poro", true], ["na parede externa, voltada para as células vizinhas", false], ["uniforme em toda a célula", false], ["nas paredes que tocam as células subsidiárias", false]],
      fb: "A parede interna mais espessa, somada às microfibrilas radiais, faz a célula curvar-se para fora quando ganha turgor, abrindo a fenda." },
    { id: "02-7", t: "mc", q: "Uma concentração alta de CO<sub>2</sub> intercelular (C<sub>i</sub>) tende a:",
      o: [["fechar os estômatos", true], ["abrir os estômatos ao máximo", false], ["não ter efeito sobre os estômatos", false], ["romper as células-guarda", false]],
      fb: "C<sub>i</sub> alto sinaliza que a demanda de carbono está satisfeita: o poro fecha para poupar água." },
    { id: "02-8", t: "mc", q: "No fechamento estomático induzido por ABA, o passo inicial na membrana das células-guarda é:",
      o: [["ativação de canais de ânions (SLAC1), com efluxo de Cl<sup>−</sup>/malato e despolarização", true], ["ativação da H<sup>+</sup>-ATPase e hiperpolarização", false], ["influxo de K<sup>+</sup> pelos canais KAT1", false], ["síntese de amido a partir de malato", false]],
      fb: "O ABA eleva Ca<sup>2+</sup> e pH, abre SLAC1 (saída de ânions), despolariza a membrana, ativa canais de saída de K<sup>+</sup> (GORK) e reverte a abertura." },
    { id: "02-9", t: "vf", q: "As células-guarda têm plasmodesmos abundantes conectando-as às células epidérmicas vizinhas.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "Elas são osmoticamente isoladas (sem plasmodesmos funcionais), o que permite manter gradientes de soluto próprios." },
    { id: "02-10", t: "mc", q: "As gramíneas têm células-guarda em forma de halteres e células subsidiárias. A consequência funcional é:",
      o: [["cinética estomática muito rápida (abrem e fecham depressa)", true], ["estômatos permanentemente abertos", false], ["ausência de resposta à luz", false], ["transpiração noturna elevada", false]],
      fb: "As células subsidiárias funcionam como reservatório de íons, acelerando as trocas de turgor." },
    { id: "02-11", t: "mc", q: "A luz vermelha promove a abertura estomática principalmente porque:",
      o: [["ativa a fotossíntese do mesofilo, que consome CO<sub>2</sub> e baixa o C<sub>i</sub>", true], ["é percebida diretamente pela fototropina", false], ["aquece as células-guarda", false], ["degrada o ABA foliar", false]],
      fb: "A resposta à luz vermelha é indireta, via queda do C<sub>i</sub> pela fotossíntese; a da luz azul é direta, via fototropina." },
    { id: "02-12", t: "mc", q: "No mesmo ambiente quente e seco, uma planta C4 comparada a uma C3 tende a ter:",
      o: [["eficiência do uso da água (A/E) maior, com g<sub>s</sub> menor", true], ["A/E menor, porque abre mais os estômatos", false], ["A/E igual, pois o mecanismo estomático é idêntico", false], ["transpiração maior para o mesmo A", false]],
      fb: "C4 concentra CO<sub>2</sub> internamente e sustenta A alta com condutância menor — daí a melhor A/E em clima quente e seco." },
    { id: "02-13", t: "vf", q: "O vapor d'água e o CO<sub>2</sub> atravessam o mesmo poro estomático, em sentidos opostos.",
      o: [["Verdadeiro", true], ["Falso", false]],
      fb: "Por isso abrir o estômato é sempre um compromisso: ganha-se CO<sub>2</sub> para a fotossíntese e perde-se água por transpiração." }
  ],

  "03-nutricao": [
    { id: "03-1", t: "mc", q: "Uma planta mostra clorose internerval intensa apenas nas folhas jovens do ápice; as folhas velhas seguem verdes. Deficiência mais provável:",
      o: [["Ferro", true], ["Nitrogênio", false], ["Magnésio", false], ["Potássio", false]],
      fb: "Fe é imóvel no floema: o sintoma aparece primeiro nas folhas novas. A clorose internerval de Mg seria nas folhas velhas." },
    { id: "03-2", t: "mc", q: "Por que o sintoma de deficiência de nitrogênio começa pelas folhas mais velhas?",
      o: [["O N é móvel: é remobilizado das folhas maduras para os tecidos jovens.", true], ["As folhas velhas transpiram mais e perdem N pelo xilema.", false], ["As folhas novas têm reservas próprias de N.", false], ["O N precipita nas nervuras das folhas velhas.", false]],
      fb: "Sob deficiência, proteínas e clorofila das folhas velhas são degradadas e o N segue pelo floema para os drenos jovens." },
    { id: "03-3", t: "mc", q: "Fornecer um nutriente muito além da faixa adequada geralmente:",
      o: [["não aumenta o crescimento (consumo de luxo) e, em excesso, pode reduzi-lo por toxicidade", true], ["aumenta o crescimento de forma proporcional", false], ["converte o macronutriente em micronutriente", false], ["corrige qualquer outra deficiência", false]],
      fb: "Acima do platô, o nutriente extra é absorvido sem ganho de biomassa; doses muito altas (sobretudo de micronutrientes) causam toxicidade." },
    { id: "03-4", t: "mc", q: "Os critérios de essencialidade de um elemento (não completar o ciclo sem ele, função insubstituível, participação direta no metabolismo) foram propostos por:",
      o: [["Arnon & Stout", true], ["Farquhar & von Caemmerer", false], ["Cholodny & Went", false], ["Skoog & Miller", false]],
      fb: "Arnon & Stout (1939) definiram os três critérios que classificam um elemento como essencial." },
    { id: "03-5", t: "mc", q: "O grupo dos macronutrientes é:",
      o: [["N, P, K, Ca, Mg, S", true], ["N, P, K, Fe, Zn, B", false], ["Fe, Mn, Zn, Cu, B, Mo", false], ["C, H, O, N, P, K", false]],
      fb: "Macronutrientes: N, P, K, Ca, Mg, S. Micronutrientes: Fe, Mn, Zn, Cu, B, Mo, Cl, Ni." },
    { id: "03-6", t: "mc", q: "O magnésio é indispensável porque:",
      o: [["é o átomo central da molécula de clorofila (além de cofator enzimático)", true], ["compõe a parede celular", false], ["é o principal ânion do vacúolo", false], ["faz parte dos grupos heme", false]],
      fb: "Sem Mg não há clorofila funcional; a deficiência dá clorose internerval nas folhas velhas (Mg é móvel)." },
    { id: "03-7", t: "mc", q: "A deficiência de cálcio manifesta-se primeiro em:",
      o: [["folhas novas e gemas (morte de pontos de crescimento; podridão apical em frutos)", true], ["folhas velhas, com clorose uniforme", false], ["raízes, com escurecimento", false], ["nervuras das folhas maduras", false]],
      fb: "Ca é praticamente imóvel no floema: fica retido onde foi depositado e o sintoma surge nos tecidos jovens." },
    { id: "03-8", t: "mc", q: "A principal via de chegada de NO<sub>3</sub><sup>−</sup>, Ca<sup>2+</sup> e Mg<sup>2+</sup> à superfície da raiz é:",
      o: [["fluxo de massa (arrastados pela água da transpiração)", true], ["difusão pura", false], ["transporte ativo no solo", false], ["interceptação radicular", false]],
      fb: "Fluxo de massa domina para íons abundantes na solução do solo; a difusão domina para P e K, que se esgotam junto à raiz." },
    { id: "03-9", t: "mc", q: "Para fósforo e potássio, a via de chegada à raiz predominante é:",
      o: [["difusão pelo gradiente criado pela absorção", true], ["fluxo de massa", false], ["gutação", false], ["transporte pelo floema", false]],
      fb: "P e K têm baixa concentração na solução do solo e são absorvidos rapidamente; forma-se uma zona de depleção e eles chegam por difusão." },
    { id: "03-10", t: "vf", q: "Nutrientes imóveis no floema (como Ca e Fe) mostram os sintomas de deficiência primeiro nas folhas velhas.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "É o contrário: como não são redistribuídos, o sintoma aparece nas folhas novas e nos meristemas." },
    { id: "03-11", t: "mc", q: "A deficiência de potássio produz tipicamente:",
      o: [["clorose e necrose nas margens e pontas das folhas velhas", true], ["arroxeamento das folhas jovens", false], ["clorose internerval nas folhas novas", false], ["deformação das gemas apicais", false]],
      fb: "K é móvel; o sintoma começa pelas folhas maduras, com necrose marginal — reflexo do papel do K na osmorregulação e no turgor." },
    { id: "03-12", t: "mc", q: "A absorção de NO<sub>3</sub><sup>−</sup> pela membrana da célula da raiz é:",
      o: [["ativa: simporte NO<sub>3</sub><sup>−</sup>/H<sup>+</sup> energizado pela H<sup>+</sup>-ATPase", true], ["passiva, por canais a favor do gradiente", false], ["por endocitose de partículas de solo", false], ["exclusivamente pela via apoplástica até o xilema", false]],
      fb: "A H<sup>+</sup>-ATPase bombeia H<sup>+</sup> para fora e o gradiente resultante puxa o NO<sub>3</sub><sup>−</sup> para dentro junto com H<sup>+</sup>." },
    { id: "03-13", t: "mc", q: "Transportadores de alta afinidade (HATS) diferem dos de baixa afinidade (LATS) porque:",
      o: [["operam bem quando a concentração externa do íon é baixa", true], ["só funcionam em concentração externa alta", false], ["transportam água, não íons", false], ["não dependem de energia", false]],
      fb: "HATS saturam em micromolar e garantem absorção em solo pobre; LATS atuam em concentração alta (milimolar)." }
  ],

  "04-floema": [
    { id: "04-1", t: "mc", q: "Anela-se (remove-se um anel de casca com floema) o caule logo abaixo de um ramo com folhas. Semanas depois, acima do anel espera-se:",
      o: [["acúmulo de fotoassimilados e intumescimento; a longo prazo, morte das raízes", true], ["murcha imediata das folhas por falta de água", false], ["nenhuma alteração: o xilema compensa", false], ["aumento da fotossíntese nas folhas", false]],
      fb: "O anelamento interrompe o floema, não o xilema: a água sobe, mas o açúcar não desce; acumula acima do anel e as raízes definham." },
    { id: "04-2", t: "mc", q: "Uma folha jovem sombreada, com fotossíntese líquida próxima de zero, em relação ao floema comporta-se como:",
      o: [["dreno, pois importa carbono para sua expansão e respiração", true], ["fonte, pois toda folha exporta açúcar", false], ["nem fonte nem dreno: está isolada do sistema vascular", false], ["fonte apenas à noite", false]],
      fb: "O papel fonte/dreno depende do balanço de carbono, não da identidade do órgão. Balanço negativo → importa pelo floema." },
    { id: "04-3", t: "mc", q: "Na hipótese do fluxo de pressão, o que mantém o gradiente de pressão entre fonte e dreno?",
      o: [["o carregamento contínuo de sacarose na fonte e a descarga/consumo contínuo no dreno", true], ["a contração ativa das placas crivadas", false], ["a gravidade", false], ["a transpiração das folhas fonte", false]],
      fb: "O fluxo é passivo (de massa), mas depende de dois processos ativos nas pontas: carregar açúcar na fonte e descarregá-lo no dreno." },
    { id: "04-4", t: "mc", q: "Na maturidade, os elementos de tubo crivado do floema são:",
      o: [["células vivas, porém sem núcleo, com citoplasma reduzido a uma camada parietal", true], ["células mortas, ocas, como os elementos de vaso", false], ["células com núcleo grande e muitos cloroplastos", false], ["fibras lignificadas", false]],
      fb: "São vivas, mas anucleadas; dependem da célula companheira para proteínas, ATP e carregamento." },
    { id: "04-5", t: "mc", q: "A célula companheira do floema é responsável por:",
      o: [["carregar sacarose no tubo crivado e fornecer-lhe ATP e proteínas", true], ["conduzir a maior parte da seiva", false], ["fazer a fotossíntese da folha", false], ["ocluir as placas crivadas em caso de dano", false]],
      fb: "O elemento de tubo crivado, sem núcleo, é mantido metabolicamente pela célula companheira adjacente." },
    { id: "04-6", t: "mc", q: "No carregamento apoplástico do floema, a sacarose entra no complexo tubo crivado–célula companheira por:",
      o: [["simporte sacarose/H<sup>+</sup> (SUC), contra o gradiente, energizado pela H<sup>+</sup>-ATPase", true], ["difusão simples pelos plasmodesmos", false], ["endocitose", false], ["canais de sacarose a favor do gradiente", false]],
      fb: "O transporte ativo concentra sacarose 2–5× a do mesofilo, gerando o Ψ<sub>p</sub> alto necessário na fonte." },
    { id: "04-7", t: "mc", q: "O carregamento simplástico (\"armadilha de polímeros\", comum em árvores) funciona porque:",
      o: [["a sacarose é convertida em rafinose/estaquiose, grandes demais para difundir de volta", true], ["a sacarose é bombeada contra gradiente pela H<sup>+</sup>-ATPase", false], ["os plasmodesmos se fecham após a entrada", false], ["a sacarose é oxidada a CO<sub>2</sub> no tubo", false]],
      fb: "Oligossacarídeos maiores não retornam pelos plasmodesmos estreitos das células intermediárias, mantendo o gradiente." },
    { id: "04-8", t: "mc", q: "A direção do transporte no floema é:",
      o: [["sempre da fonte para o dreno, podendo ser para cima ou para baixo", true], ["sempre de baixo para cima, como no xilema", false], ["sempre de cima para baixo", false], ["definida pela anatomia do feixe, não pelo balanço de pressão", false]],
      fb: "Em feixes diferentes, o floema pode transportar nos dois sentidos ao mesmo tempo, conforme o balanço local de pressão." },
    { id: "04-9", t: "vf", q: "O floema transporta seiva apenas de cima para baixo (das folhas para as raízes).",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "O floema é bidirecional: leva açúcar de qualquer fonte para qualquer dreno, inclusive para cima (frutos, gemas apicais)." },
    { id: "04-10", t: "mc", q: "A transição dreno–fonte de uma folha em desenvolvimento ocorre:",
      o: [["quando ela atinge ~30–60% do tamanho final, começando pela ponta", true], ["assim que o primórdio foliar aparece", false], ["só depois da senescência", false], ["nunca: uma folha é fonte a vida toda", false]],
      fb: "A folha nasce dreno (importa carbono para crescer) e passa a exportar quando amadurece, a partir da ponta." },
    { id: "04-11", t: "mc", q: "Ralear (remover) parte dos frutos de uma planta tende a:",
      o: [["aumentar o tamanho dos frutos remanescentes", true], ["reduzir o tamanho de todos os frutos", false], ["não afetar a partição de assimilados", false], ["transformar as folhas em drenos", false]],
      fb: "Com menos drenos competindo pela mesma fonte, cada fruto restante recebe uma fração maior do fluxo de fotoassimilados." },
    { id: "04-12", t: "mc", q: "Comparada à seiva do xilema, a seiva do floema:",
      o: [["é concentrada em sacarose (10–30%) e carrega aminoácidos, hormônios e RNA", true], ["é praticamente água pura", false], ["contém apenas íons minerais", false], ["move-se por tensão (pressão negativa)", false]],
      fb: "O xilema conduz uma solução diluída sob tensão; o floema, uma solução açucarada sob pressão positiva." },
    { id: "04-13", t: "mc", q: "A \"força de um dreno\" é melhor descrita como:",
      o: [["tamanho do dreno × atividade metabólica (taxa de consumo/estocagem de sacarose)", true], ["apenas o tamanho do órgão", false], ["a distância até a fonte mais próxima", false], ["a quantidade de clorofila que ele contém", false]],
      fb: "Um dreno grande mas inativo importa pouco; a manutenção do gradiente exige consumo ou estocagem contínua de sacarose." }
  ],

  "05-fotossintese": [
    { id: "05-1", t: "mc", q: "Numa planta C3, aumentar a temperatura da folha de 25 °C para 38 °C, com luz e C<sub>i</sub> constantes, tende a:",
      o: [["reduzir A líquida, porque a oxigenação da RuBP aumenta e Γ* sobe", true], ["aumentar A líquida, pois a rubisco fica mais rápida sem custo", false], ["não alterar A: a temperatura só afeta as reações luminosas", false], ["zerar a respiração mitocondrial", false]],
      fb: "Com o calor, a especificidade da rubisco pelo CO<sub>2</sub> cai e a solubilidade relativa do CO<sub>2</sub> diminui: mais fotorrespiração, A líquida menor." },
    { id: "05-2", t: "mc", q: "Plantas C4 mantêm assimilação alta mesmo com estômatos relativamente fechados (C<sub>i</sub> baixo) porque:",
      o: [["a PEP-carboxilase pré-fixa carbono e concentra CO<sub>2</sub> na bainha vascular, saturando a rubisco", true], ["não possuem rubisco", false], ["fazem fotossíntese apenas à noite", false], ["dispensam as reações luminosas", false]],
      fb: "A bomba bioquímica de carbono eleva o CO<sub>2</sub> ao redor da rubisco a valores que suprimem a oxigenação." },
    { id: "05-3", t: "mc", q: "Em baixa irradiância, o trecho inicial quase linear da curva de luz da fotossíntese é determinado por:",
      o: [["o suprimento de ATP e NADPH pelas reações luminosas (limitação por transporte de elétrons)", true], ["a capacidade máxima de carboxilação da rubisco (V<sub>cmax</sub>)", false], ["a condutância do mesofilo ao CO<sub>2</sub>", false], ["a concentração de O<sub>2</sub> no ar", false]],
      fb: "Sob pouca luz cada fóton extra rende quase um incremento proporcional de A: a fase é limitada por J." },
    { id: "05-4", t: "mc", q: "As reações dependentes de luz da fotossíntese produzem diretamente:",
      o: [["ATP, NADPH e O<sub>2</sub>", true], ["glicose e O<sub>2</sub>", false], ["ATP e CO<sub>2</sub>", false], ["triose-fosfato e água", false]],
      fb: "A energia luminosa gera poder redutor (NADPH) e ATP; o ciclo de Calvin usa esses produtos para fixar carbono." },
    { id: "05-5", t: "mc", q: "No fotossistema II, os elétrons que substituem os que saem do P680 vêm de:",
      o: [["oxidação da água (fotólise), com liberação de O<sub>2</sub>", true], ["oxidação do NADPH", false], ["redução do CO<sub>2</sub>", false], ["quebra do ATP", false]],
      fb: "O complexo de evolução de oxigênio oxida 2 H<sub>2</sub>O → O<sub>2</sub> + 4 H<sup>+</sup> + 4 e<sup>−</sup>." },
    { id: "05-6", t: "mc", q: "Para cada CO<sub>2</sub> fixado no ciclo de Calvin, são consumidos aproximadamente:",
      o: [["3 ATP e 2 NADPH", true], ["1 ATP e 1 NADPH", false], ["2 ATP e 3 NADPH", false], ["6 ATP e 6 NADPH", false]],
      fb: "Carboxilação, redução e regeneração da RuBP custam 3 ATP e 2 NADPH por CO<sub>2</sub>; 3 voltas geram 1 triose-fosfato líquida." },
    { id: "05-7", t: "mc", q: "A fotorrespiração tem início quando a rubisco:",
      o: [["adiciona O<sub>2</sub> à RuBP (oxigenação), gerando 2-fosfoglicolato", true], ["carboxila a RuBP normalmente", false], ["hidrolisa ATP", false], ["reduz o NADP<sup>+</sup>", false]],
      fb: "O sítio ativo da rubisco não distingue bem CO<sub>2</sub> de O<sub>2</sub>; a oxigenação inicia uma via cara de recuperação do glicolato." },
    { id: "05-8", t: "mc", q: "A via de recuperação do 2-fosfoglicolato (fotorrespiração) percorre:",
      o: [["cloroplasto, peroxissomo e mitocôndria", true], ["apenas o cloroplasto", false], ["cloroplasto e vacúolo", false], ["retículo endoplasmático e Golgi", false]],
      fb: "Ela consome ATP e libera CO<sub>2</sub> e NH<sub>3</sub> já fixados, atravessando três organelas." },
    { id: "05-9", t: "mc", q: "O ponto de compensação de CO<sub>2</sub> é:",
      o: [["alto em C3 (40–70 ppm) e próximo de zero em C4", true], ["igual em C3 e C4", false], ["alto em C4 e baixo em C3", false], ["sempre 400 ppm", false]],
      fb: "A supressão da fotorrespiração em C4 permite assimilação líquida positiva mesmo com CO<sub>2</sub> muito baixo." },
    { id: "05-10", t: "mc", q: "No metabolismo CAM, a fixação inicial de CO<sub>2</sub> pela PEP-carboxilase ocorre:",
      o: [["à noite, com os estômatos abertos", true], ["de dia, com os estômatos abertos", false], ["de dia, com os estômatos fechados", false], ["continuamente, dia e noite", false]],
      fb: "O CO<sub>2</sub> noturno é estocado como malato; de dia, com estômatos fechados, o malato é descarboxilado e a rubisco atua." },
    { id: "05-11", t: "vf", q: "A fotorrespiração aumenta a eficiência da fotossíntese em plantas C3 sob calor.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "Ela consome O<sub>2</sub> e ATP e libera CO<sub>2</sub> já fixado, reduzindo a assimilação líquida — problema que C4 e CAM contornam." },
    { id: "05-12", t: "mc", q: "Sob excesso de luz, o mecanismo de dissipação térmica (NPQ), via ciclo das xantofilas, serve para:",
      o: [["dissipar o excesso de energia de excitação como calor, protegendo o aparato fotossintético", true], ["aumentar a produção de O<sub>2</sub>", false], ["acelerar o ciclo de Calvin", false], ["fechar os estômatos", false]],
      fb: "É uma válvula de fotoproteção que evita danos por excesso de elétrons quando a fixação de carbono não acompanha a luz." },
    { id: "05-13", t: "mc", q: "A triose-fosfato exportada do cloroplasto para o citosol é usada principalmente para:",
      o: [["sintetizar sacarose, que será transportada pelo floema", true], ["formar amido dentro do próprio citosol", false], ["reduzir o NADP<sup>+</sup>", false], ["ser oxidada de volta a CO<sub>2</sub> imediatamente", false]],
      fb: "No citosol a triose-fosfato vira sacarose (transporte a longa distância); o que fica no cloroplasto é estocado como amido." }
  ],

  "06-respiracao": [
    { id: "06-1", t: "mc", q: "Uma raiz em solo alagado passa a fermentar. Para manter a mesma produção de ATP, o consumo de glicose:",
      o: [["aumenta muito, porque a fermentação rende ~15× menos ATP por glicose", true], ["diminui, porque a fermentação é mais eficiente", false], ["não muda, pois o ATP vem sempre da glicólise", false], ["cai a zero", false]],
      fb: "Aeróbio ≈ 30 ATP/glicose; fermentação = 2 ATP/glicose. Para o mesmo ATP, o consumo de substrato dispara e as reservas se esgotam." },
    { id: "06-2", t: "mc", q: "Uma semente oleaginosa em germinação apresenta quociente respiratório (QR) ≈ 0,7. Isso indica que ela está:",
      o: [["oxidando lipídios, que exigem mais O<sub>2</sub> por CO<sub>2</sub> produzido", true], ["fermentando por falta de O<sub>2</sub>", false], ["fixando CO<sub>2</sub> pela fotossíntese", false], ["oxidando carboidratos puros", false]],
      fb: "Ácidos graxos são muito reduzidos: sua oxidação consome relativamente mais O<sub>2</sub>, logo QR = CO<sub>2</sub>/O<sub>2</sub> ≈ 0,7." },
    { id: "06-3", t: "mc", q: "A oxidase alternativa (AOX) das plantas transfere elétrons ao O<sub>2</sub> sem bombear prótons. A consequência direta é:",
      o: [["menos ATP por NADH oxidado e liberação de energia como calor", true], ["mais ATP, por encurtar o caminho dos elétrons", false], ["produção de O<sub>2</sub> em vez de consumo", false], ["parada total da glicólise", false]],
      fb: "Sem contribuir para o gradiente de H<sup>+</sup>, a energia dos elétrons vira calor (termogênese) e a cadeia fica menos reduzida (menos ROS)." },
    { id: "06-4", t: "mc", q: "A glicólise ocorre no ___ e tem saldo líquido de ___.",
      o: [["citosol; 2 ATP e 2 NADH", true], ["matriz mitocondrial; 2 ATP e 2 NADH", false], ["citosol; 30 ATP", false], ["membrana interna da mitocôndria; 4 FADH<sub>2</sub>", false]],
      fb: "A glicólise é citosólica; cliva a glicose (6C) em dois piruvatos (3C), rendendo 2 ATP e 2 NADH líquidos." },
    { id: "06-5", t: "mc", q: "Na respiração aeróbia, o aceptor final de elétrons da cadeia transportadora é:",
      o: [["o O<sub>2</sub>, formando água", true], ["o NAD<sup>+</sup>", false], ["o piruvato", false], ["o CO<sub>2</sub>", false]],
      fb: "Os elétrons de NADH e FADH<sub>2</sub> descem pelos complexos I–IV até o O<sub>2</sub>; sem O<sub>2</sub> a cadeia para." },
    { id: "06-6", t: "mc", q: "A estimativa realista de rendimento da oxidação completa de uma glicose é de aproximadamente:",
      o: [["30 ATP", true], ["2 ATP", false], ["12 ATP", false], ["100 ATP", false]],
      fb: "O total teórico ≈ 32 ATP; descontando o custo de importar NADH citosólico e o vazamento de prótons, chega-se a ~30." },
    { id: "06-7", t: "mc", q: "O ciclo do ácido cítrico ocorre:",
      o: [["na matriz mitocondrial", true], ["no citosol", false], ["na membrana externa da mitocôndria", false], ["no estroma do cloroplasto", false]],
      fb: "Oxida o acetil-CoA a 2 CO<sub>2</sub> por volta, gerando 3 NADH, 1 FADH<sub>2</sub> e 1 GTP." },
    { id: "06-8", t: "mc", q: "Na fermentação alcoólica, o papel de reduzir o piruvato (via acetaldeído) a etanol é:",
      o: [["regenerar NAD<sup>+</sup> para a glicólise continuar", true], ["produzir ATP adicional diretamente", false], ["consumir o O<sub>2</sub> acumulado", false], ["sintetizar acetil-CoA para o ciclo de Krebs", false]],
      fb: "Sem a cadeia transportadora, o NADH não é reoxidado; a fermentação regenera NAD<sup>+</sup> e mantém a única fonte de ATP funcionando." },
    { id: "06-9", t: "mc", q: "O quociente respiratório (QR) de carboidratos é aproximadamente:",
      o: [["1,0", true], ["0,7", false], ["1,3", false], ["0,3", false]],
      fb: "C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub> → 6 CO<sub>2</sub> + 6 H<sub>2</sub>O: 6 CO<sub>2</sub>/6 O<sub>2</sub> = 1,0. Lipídios ≈ 0,7; ácidos orgânicos > 1." },
    { id: "06-10", t: "vf", q: "A temperatura altera o rendimento de ATP por molécula de glicose oxidada.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "A temperatura muda a TAXA da respiração (Q<sub>10</sub> ≈ 2), não o rendimento por molécula, que é fixado pela estequiometria." },
    { id: "06-11", t: "mc", q: "O Q<sub>10</sub> da respiração vegetal é de cerca de 2. Isso significa que:",
      o: [["a taxa respiratória aproximadamente dobra a cada 10 °C de aumento, até ~35–40 °C", true], ["a respiração cessa acima de 10 °C", false], ["são necessários 10 O<sub>2</sub> por glicose", false], ["o rendimento cai pela metade a cada 10 °C", false]],
      fb: "Acima de ~35–40 °C enzimas e membranas se desestruturam e a taxa despenca, apesar do substrato disponível." },
    { id: "06-12", t: "mc", q: "A via das pentoses-fosfato oxida a glicose-6-fosfato para gerar principalmente:",
      o: [["NADPH e precursores de biossíntese (ribose-5-P, eritrose-4-P)", true], ["ATP em grande quantidade", false], ["etanol e CO<sub>2</sub>", false], ["FADH<sub>2</sub> para a cadeia respiratória", false]],
      fb: "É uma rota de poder redutor (NADPH) para biossíntese e de esqueletos de carbono, paralela à glicólise." },
    { id: "06-13", t: "mc", q: "A fosforilação em nível de substrato (síntese de ATP/GTP por transferência direta de fosfato) ocorre em:",
      o: [["glicólise e ciclo do ácido cítrico", true], ["apenas na cadeia transportadora de elétrons", false], ["apenas na fosforilação oxidativa", false], ["no ciclo de Calvin", false]],
      fb: "Na cadeia, o ATP vem da quimiosmose (ATP-sintase). Os poucos ATP/GTP diretos são feitos na glicólise e no ciclo de Krebs." }
  ],

  "07-hormonios": [
    { id: "07-1", t: "mc", q: "Um explante de calo é transferido para meio com alta auxina e baixa citocinina. O resultado mais provável:",
      o: [["formação de raízes (rizogênese)", true], ["formação de gemas e parte aérea", false], ["morte do tecido por toxicidade", false], ["floração imediata", false]],
      fb: "Razão auxina/citocinina alta favorece a organogênese radicular; a relação inversa induz parte aérea; razões próximas mantêm o calo." },
    { id: "07-2", t: "mc", q: "Após a decapitação do ápice caulinar, as gemas laterais brotam. Aplicar pasta de auxina no corte:",
      o: [["restaura a inibição das gemas laterais, imitando o ápice removido", true], ["acelera ainda mais o brotamento lateral", false], ["não tem efeito, pois a auxina não é transportada", false], ["mata as gemas laterais", false]],
      fb: "A auxina exógena substitui a fonte apical: transportada basipetamente, reprime o brotamento lateral (dominância apical)." },
    { id: "07-3", t: "mc", q: "Sementes de muitas espécies só germinam quando:",
      o: [["a razão GA/ABA aumenta (queda de ABA e/ou síntese de GA)", true], ["ABA e GA sobem juntos", false], ["o etileno substitui a GA em todas as espécies", false], ["a razão GA/ABA diminui", false]],
      fb: "Dormência e germinação são um balanço GA × ABA; a germinação prossegue quando essa razão cruza um limiar." },
    { id: "07-4", t: "mc", q: "Qual hormônio vegetal possui transporte polar direcionado (basípeto no caule), mediado por proteínas de efluxo específicas?",
      o: [["auxina (AIA), via proteínas PIN", true], ["giberelina, via proteínas GID", false], ["ácido abscísico, via proteínas PYR/PYL", false], ["etileno, via receptores ETR", false]],
      fb: "A posição assimétrica das proteínas PIN na face basal da célula define a direção do fluxo de auxina." },
    { id: "07-5", t: "mc", q: "As proteínas PIN, transportadoras de efluxo de auxina, localizam-se preferencialmente:",
      o: [["na face basal da célula, o que direciona o fluxo de auxina para baixo", true], ["na face apical da célula", false], ["distribuídas uniformemente na membrana", false], ["apenas no tonoplasto (membrana do vacúolo)", false]],
      fb: "A auxina entra por difusão/AUX1 e só sai pelas PIN; a polaridade da PIN estabelece o transporte polar." },
    { id: "07-6", t: "mc", q: "Na germinação de cereais, a giberelina produzida pelo embrião age no endosperma induzindo:",
      o: [["a síntese de α-amilase, que mobiliza o amido de reserva", true], ["o fechamento dos estômatos do embrião", false], ["a síntese de ABA", false], ["a lignificação da parede", false]],
      fb: "A GA dispara enzimas hidrolíticas na camada de aleurona; os açúcares liberados alimentam o crescimento da plântula." },
    { id: "07-7", t: "mc", q: "A citocinina é sintetizada principalmente:",
      o: [["nos ápices radiculares, sendo transportada para a parte aérea pelo xilema", true], ["nas folhas maduras, e transportada pelo floema", false], ["apenas em frutos em amadurecimento", false], ["nas sementes dormentes", false]],
      fb: "Por isso a razão citocinina/auxina que chega à parte aérea informa o estado do sistema radicular." },
    { id: "07-8", t: "mc", q: "São efeitos típicos do etileno:",
      o: [["amadurecimento de frutos, senescência, abscisão e respostas ao alagamento", true], ["alongamento de entrenós e indução da floração em roseta", false], ["fechamento estomático e dormência de sementes", false], ["divisão celular e retardo da senescência", false]],
      fb: "As demais alternativas descrevem, respectivamente, a giberelina, o ABA e a citocinina." },
    { id: "07-9", t: "mc", q: "São efeitos típicos do ácido abscísico (ABA):",
      o: [["fechamento estomático, dormência de sementes e gemas, tolerância a estresse", true], ["amadurecimento de frutos e abscisão", false], ["alongamento celular e dominância apical", false], ["divisão celular e formação de parte aérea", false]],
      fb: "O ABA é o hormônio do estresse hídrico e da dormência; inibe a germinação." },
    { id: "07-10", t: "vf", q: "A resposta de um tecido a um hormônio depende apenas da concentração do hormônio.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "Depende também da sensibilidade do tecido (receptores, transdução), da fase do desenvolvimento e da interação com outros hormônios." },
    { id: "07-11", t: "mc", q: "Muitas vias hormonais atuam por degradação regulada de repressores. Na sinalização por auxina, o alvo degradado é:",
      o: [["as proteínas AUX/IAA, liberando os fatores de transcrição ARF", true], ["as proteínas DELLA, liberando fatores PIF", false], ["as proteínas JAZ", false], ["a própria auxina", false]],
      fb: "Auxina → SCF<sup>TIR1</sup> ubiquitina as AUX/IAA → proteassomo as degrada → ARFs livres ativam genes de resposta em minutos." },
    { id: "07-12", t: "mc", q: "As estrigolactonas atuam sobretudo:",
      o: [["inibindo a ramificação (gemas laterais) e sinalizando com fungos micorrízicos", true], ["promovendo o amadurecimento de frutos", false], ["fechando os estômatos sob seca", false], ["induzindo a floração de dia longo", false]],
      fb: "São hormônios de perfilhamento/ramificação e mediadores da simbiose com micorrizas arbusculares." },
    { id: "07-13", t: "mc", q: "Num meio de cultura com alta citocinina e baixa auxina, o explante tende a formar:",
      o: [["gemas e parte aérea (caulogênese)", true], ["raízes (rizogênese)", false], ["apenas calo indiferenciado", false], ["frutos partenocárpicos", false]],
      fb: "É a fase de multiplicação de brotos na micropropagação; depois passa-se a um meio rico em auxina para enraizar." }
  ],

  "08-luz": [
    { id: "08-1", t: "mc", q: "Uma planta de dia curto é mantida em noites de 14 h. Um flash de luz vermelha no meio de cada noite:",
      o: [["inibe a floração: nenhuma metade da noite atinge o comprimento crítico", true], ["acelera a floração, pois o total de escuro continua alto", false], ["não tem efeito: só a luz azul afeta o fotoperiodismo", false], ["induz dormência das gemas", false]],
      fb: "A quebra de noite reconverte Pr→Pfr e reinicia a medição; duas noites de 7 h ficam abaixo do crítico (~11 h)." },
    { id: "08-2", t: "mc", q: "O efeito de um flash de luz vermelha durante a noite pode ser cancelado por:",
      o: [["um flash imediato de luz vermelho-distante logo depois", true], ["um flash de luz azul", false], ["baixar a temperatura por alguns minutos", false], ["um flash de luz vermelha adicional", false]],
      fb: "Vermelho converte Pr→Pfr; vermelho-distante reverte Pfr→Pr. A reversibilidade V/VD é a assinatura do fitocromo." },
    { id: "08-3", t: "mc", q: "Numa planta de dia longo em ambiente de dias curtos, uma quebra de noite tende a:",
      o: [["promover a floração, por encurtar a noite ininterrupta abaixo do crítico", true], ["inibir a floração, como faz nas plantas de dia curto", false], ["não ter efeito em plantas de dia longo", false], ["induzir tuberização", false]],
      fb: "Plantas de dia longo florescem com noites curtas; partir a noite em duas simula essa condição." },
    { id: "08-4", t: "mc", q: "A forma Pr do fitocromo absorve luz ___ e, ao fazê-lo, converte-se em ___.",
      o: [["vermelha (~660 nm); Pfr", true], ["vermelho-distante (~730 nm); Pfr", false], ["azul (~450 nm); Pr", false], ["verde (~550 nm); Pfr", false]],
      fb: "Pr absorve vermelho e vira Pfr; Pfr absorve vermelho-distante e volta a Pr." },
    { id: "08-5", t: "mc", q: "A forma fisiologicamente ativa do fitocromo é:",
      o: [["Pfr", true], ["Pr", false], ["ambas igualmente ativas", false], ["nenhuma: o fitocromo é apenas um pigmento acessório", false]],
      fb: "Pfr migra ao núcleo e regula a transcrição. Sob luz solar, rica em vermelho, predomina Pfr." },
    { id: "08-6", t: "vf", q: "O fotoperiodismo mede o comprimento do dia, não o da noite.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "Interromper a noite com um flash inverte a resposta; interromper o dia com escuro não faz efeito. O que é medido é a duração da escuridão contínua." },
    { id: "08-7", t: "mc", q: "Criptocromos e fototropinas são fotorreceptores que percebem principalmente:",
      o: [["luz azul e UV-A", true], ["luz vermelha e vermelho-distante", false], ["luz verde", false], ["radiação infravermelha", false]],
      fb: "Fitocromos percebem vermelho/vermelho-distante; criptocromos/fototropinas, azul/UV-A; o UVR8, UV-B." },
    { id: "08-8", t: "mc", q: "O \"florígeno\" é:",
      o: [["a proteína FT, produzida na folha induzida e transportada pelo floema até o meristema apical", true], ["um pigmento do fitocromo", false], ["um açúcar acumulado nas gemas florais", false], ["o hormônio giberelina", false]],
      fb: "Basta uma folha exposta ao fotoperíodo indutivo para produzir FT e induzir a floração da planta inteira." },
    { id: "08-9", t: "mc", q: "Numa razão vermelho:vermelho-distante baixa (sombra de vizinhos), a planta responde com a \"síndrome de evitação de sombra\", que inclui:",
      o: [["alongamento acentuado, dominância apical reforçada e floração antecipada", true], ["nanismo e ramificação intensa", false], ["fechamento estomático permanente", false], ["perda das folhas superiores", false]],
      fb: "A queda de Pfr sinaliza competição por luz; a planta investe em crescer para cima e acelera o ciclo reprodutivo." },
    { id: "08-10", t: "vf", q: "A percepção do fotoperíodo que dispara a floração ocorre no meristema apical.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "A percepção ocorre nas folhas; o sinal (FT) é enviado ao meristema apical, onde a transição floral acontece." },
    { id: "08-11", t: "mc", q: "Uma planta de dia curto floresce quando a noite ininterrupta:",
      o: [["excede um valor crítico", true], ["é menor que um valor crítico", false], ["dura exatamente 12 h", false], ["é interrompida por um flash de luz", false]],
      fb: "\"Dia curto\" na prática significa \"noite longa\": são plantas de outono/inverno. As de dia longo florescem quando a noite é curta." },
    { id: "08-12", t: "mc", q: "O desestiolamento induzido por Pfr, quando a plântula emerge no claro, inclui:",
      o: [["inibição do alongamento do hipocótilo, abertura do gancho apical e síntese de clorofila", true], ["alongamento rápido do hipocótilo e cotilédones fechados", false], ["queda das raízes", false], ["floração imediata", false]],
      fb: "No escuro a plântula estiola (cresce depressa, amarela); a luz, via fitocromo, reprograma esse desenvolvimento." },
    { id: "08-13", t: "mc", q: "No modelo de coincidência externa, a proteína CONSTANS (CO) só induz a floração quando:",
      o: [["há luz no momento em que seu mRNA está em nível alto — o que, em dias longos, ocorre no fim da tarde", true], ["a temperatura está abaixo de 10 °C", false], ["o nível de ABA está alto", false], ["o solo está encharcado", false]],
      fb: "O relógio circadiano faz o mRNA de CO oscilar; a coincidência entre pico do mRNA e presença de luz sinaliza \"dia longo\" e induz FT." }
  ],

  "09-tropismos": [
    { id: "09-1", t: "mc", q: "Um coleóptilo é iluminado lateralmente pela direita. Onde a auxina se concentra e para onde ele se curva?",
      o: [["concentra-se à esquerda (lado sombreado); curva-se para a direita, em direção à luz", true], ["concentra-se à direita (lado iluminado); curva-se para a esquerda", false], ["distribui-se por igual; não há curvatura", false], ["concentra-se na ponta; o coleóptilo encurta", false]],
      fb: "A luz azul desvia a auxina para o lado sombreado; no coleóptilo a auxina promove o alongamento, então esse lado cresce mais e o ápice vira para a luz." },
    { id: "09-2", t: "mc", q: "Uma raiz é colocada na horizontal e a auxina acumula-se no seu lado inferior. Por que a raiz curva-se para baixo?",
      o: [["na raiz a auxina inibe o alongamento; o lado inferior cresce menos e a raiz curva-se para baixo", true], ["a auxina promove o alongamento do lado inferior", false], ["a gravidade puxa fisicamente a ponta da raiz", false], ["o lado superior perde água e murcha", false]],
      fb: "O acúmulo de auxina é o mesmo do caule; a diferença é a sensibilidade: na raiz essa concentração é inibitória." },
    { id: "09-3", t: "mc", q: "O fechamento das folhas da <em>Mimosa pudica</em> ao toque difere de um tropismo porque:",
      o: [["a direção do movimento independe da direção do estímulo e resulta de perda de turgor, não de crescimento", true], ["é irreversível e resulta de crescimento diferencial", false], ["é mediado por auxina transportada lateralmente", false], ["ocorre apenas sob luz azul", false]],
      fb: "É um movimento nástico (sismonastia): rápido, reversível, sem crescimento, e a folha sempre se dobra do mesmo jeito." },
    { id: "09-4", t: "mc", q: "A sequência da hipótese de Cholodny–Went para um tropismo é:",
      o: [["percepção do estímulo → redistribuição lateral de auxina → alongamento diferencial → curvatura", true], ["curvatura mecânica → síntese de auxina → crescimento", false], ["fechamento estomático → perda de turgor → dobramento", false], ["percepção → produção de etileno → abscisão", false]],
      fb: "O estímulo cria um gradiente transversal de auxina; os dois lados do órgão passam a alongar em taxas diferentes." },
    { id: "09-5", t: "mc", q: "Num tropismo por crescimento diferencial, o órgão curva-se:",
      o: [["para o lado que cresce menos", true], ["para o lado que cresce mais", false], ["sempre em direção ao solo", false], ["sempre para longe do estímulo", false]],
      fb: "Se um flanco alonga mais que o outro, o órgão arqueia na direção do flanco mais curto." },
    { id: "09-6", t: "mc", q: "O fototropismo é iniciado pela percepção da luz por:",
      o: [["fototropinas (fotorreceptores de luz azul)", true], ["fitocromos (luz vermelha)", false], ["clorofila a", false], ["criptocromos apenas no escuro", false]],
      fb: "As fototropinas phot1/phot2 geram o sinal transversal que relocaliza os transportadores PIN e desvia a auxina." },
    { id: "09-7", t: "mc", q: "A gravidade é percebida, no gravitropismo, por:",
      o: [["estatócitos (coifa da raiz e bainha amilífera do caule), pela sedimentação dos estatólitos", true], ["todas as células do órgão, por pressão hidrostática", false], ["os estômatos das folhas", false], ["as células companheiras do floema", false]],
      fb: "A deposição dos amiloplastos densos no fundo da célula reposiciona proteínas PIN (sobretudo PIN3), concentrando auxina no lado inferior." },
    { id: "09-8", t: "mc", q: "Os estatólitos, cuja sedimentação inicia a resposta gravitrópica, são:",
      o: [["amiloplastos densos (grãos de amido)", true], ["cloroplastos", false], ["vacúolos contráteis", false], ["mitocôndrias", false]],
      fb: "Por serem mais densos que o citosol, sedimentam conforme a orientação do órgão e indicam a direção da gravidade." },
    { id: "09-9", t: "mc", q: "Em relação à gravidade, o caule apresenta gravitropismo ___ e a raiz, gravitropismo ___.",
      o: [["negativo; positivo", true], ["positivo; negativo", false], ["negativo; negativo", false], ["nulo; positivo", false]],
      fb: "O caule cresce contra o vetor gravitacional (para cima); a raiz, a favor (para baixo)." },
    { id: "09-10", t: "vf", q: "A curva dose-resposta da auxina para o alongamento é igual no caule e na raiz.",
      o: [["Verdadeiro", false], ["Falso", true]],
      fb: "A raiz é muito mais sensível (ótimo ~10<sup>−10</sup> M); concentrações que estimulam o caule já inibem a raiz." },
    { id: "09-11", t: "mc", q: "O tigmotropismo é exemplificado por:",
      o: [["gavinhas que se enrolam ao redor de um suporte após o contato", true], ["folhas que se voltam para o sol ao longo do dia", false], ["raízes que crescem em direção à água", false], ["flores que abrem com o calor", false]],
      fb: "É o crescimento orientado pelo contato; raízes também usam tigmotropismo para desviar de obstáculos." },
    { id: "09-12", t: "mc", q: "Os movimentos násticos rápidos e reversíveis (como o da <em>Mimosa</em>) dependem de células-motoras localizadas:",
      o: [["no pulvino, na base do pecíolo ou dos folíolos", true], ["na coifa da raiz", false], ["nas células-guarda dos estômatos", false], ["no meristema apical", false]],
      fb: "A entrada e saída de K<sup>+</sup>, Cl<sup>−</sup> e água nas células do pulvino muda o turgor e move a folha em segundos." },
    { id: "09-13", t: "mc", q: "O hidrotropismo da raiz é:",
      o: [["positivo: a raiz cresce em direção ao gradiente de maior umidade", true], ["negativo: a raiz foge da água", false], ["ausente em plantas terrestres", false], ["mediado apenas por giberelina", false]],
      fb: "Em conflito com o gravitropismo, o hidrotropismo pode prevalecer e desviar a raiz para zonas mais úmidas do solo." }
  ],

  "10-estresse": [
    { id: "10-1", t: "mc", q: "Duas mudas idênticas são expostas a −4 °C. Uma passou duas semanas a 4 °C antes; a outra vinha de 22 °C. A aclimatada sofre menos dano principalmente porque:",
      o: [["acumulou açúcares e proteínas crioprotetoras e dessaturou lipídios de membrana (via CBF/COR)", true], ["tem estômatos menores", false], ["produz mais etileno", false], ["tem raízes mais profundas", false]],
      fb: "A exposição prévia ao frio moderado ativa a via ICE1–CBF, induzindo o regulon COR: membranas mais fluidas e menos gelo intracelular." },
    { id: "10-2", t: "mc", q: "Uma planta salina exclui Na<sup>+</sup> da raiz e guarda o excedente no vacúolo das células foliares. A vantagem de compartimentalizar em vez de deixar no citosol é:",
      o: [["proteger as enzimas citosólicas da toxicidade iônica e ainda usar o Na<sup>+</sup> como osmótico do vacúolo", true], ["usar o Na<sup>+</sup> como nutriente essencial", false], ["impedir totalmente a entrada de água na célula", false], ["aumentar a fotossíntese", false]],
      fb: "Enzimas do citosol são inibidas por Na<sup>+</sup> alto; os antiportes NHX sequestram-no no vacúolo e o citosol equilibra com osmólitos compatíveis." },
    { id: "10-3", t: "mc", q: "Em solo alagado, os fatores de transcrição do grupo VII ERF acumulam-se e disparam respostas à hipóxia. Por que são estáveis justamente quando falta O<sub>2</sub>?",
      o: [["na presença de O<sub>2</sub> são marcados para degradação pela via do N-terminal; sem O<sub>2</sub> escapam e se acumulam", true], ["são sintetizados apenas no escuro", false], ["o etileno os degrada quando há O<sub>2</sub>", false], ["a hipóxia aumenta sua transcrição em 100×", false]],
      fb: "A oxidação de uma cisteína N-terminal (dependente de O<sub>2</sub>) marca esses ERF para destruição; a hipóxia bloqueia a marcação." },
    { id: "10-4", t: "mc", q: "A diferença central entre aclimatação e adaptação é que:",
      o: [["a adaptação é fixada geneticamente ao longo de gerações; a aclimatação é uma resposta reversível do indivíduo", true], ["a aclimatação é permanente e a adaptação é temporária", false], ["só plantas C4 se adaptam", false], ["são sinônimos", false]],
      fb: "Xerófitas e halófitas são adaptadas; o endurecimento de uma muda antes do transplante é aclimatação." },
    { id: "10-5", t: "mc", q: "Uma planta efêmera do deserto que germina, floresce e produz sementes numa única estação chuvosa usa a estratégia de:",
      o: [["escape (completar o ciclo antes do estresse)", true], ["evitação (manter a homeostase apesar do ambiente)", false], ["tolerância (suportar o dano celular)", false], ["dormência indefinida", false]],
      fb: "Escape = fugir no tempo. Evitação = barreiras estruturais (cutícula, suculência, raízes profundas). Tolerância = bioquímica de proteção e reparo." },
    { id: "10-6", t: "mc", q: "O principal hormônio-sinal do déficit hídrico, que dispara o fechamento estomático e genes de resposta à seca, é:",
      o: [["o ácido abscísico (ABA)", true], ["o etileno", false], ["a auxina", false], ["a giberelina", false]],
      fb: "A raiz e a folha sintetizam ABA sob perda de turgor; ele fecha os estômatos (via SLAC1) e ativa o ajuste osmótico e as proteínas LEA." },
    { id: "10-7", t: "mc", q: "O estresse salino tem dois componentes de dano. São eles:",
      o: [["componente osmótico (como a seca) e toxicidade iônica de Na<sup>+</sup>/Cl<sup>−</sup>", true], ["frio e calor simultâneos", false], ["hipóxia e excesso de luz", false], ["deficiência de N e de P", false]],
      fb: "O sal baixa o potencial hídrico do solo (efeito osmótico) e, uma vez absorvido, o Na<sup>+</sup> é diretamente tóxico às células." },
    { id: "10-8", t: "mc", q: "A via SOS (Salt Overly Sensitive), ativada por Ca<sup>2+</sup> sob salinidade, atua principalmente:",
      o: [["exportando Na<sup>+</sup> da raiz para fora, pelo antiporte Na<sup>+</sup>/H<sup>+</sup> SOS1", true], ["fixando CO<sub>2</sub> extra", false], ["abrindo os estômatos", false], ["degradando a clorofila", false]],
      fb: "SOS3 percebe o Ca<sup>2+</sup>, ativa a quinase SOS2, que ativa o antiporte SOS1 na membrana plasmática das células da raiz." },
    { id: "10-9", t: "mc", q: "Sob estresse térmico, o fator de transcrição HSF dispara a síntese de:",
      o: [["proteínas de choque térmico (HSP), que atuam como chaperonas", true], ["proteínas anticongelantes", false], ["aquaporinas", false], ["PEP-carboxilase", false]],
      fb: "As HSP renaturamou marcam para degradação as proteínas que começam a desdobrar com o calor." },
    { id: "10-10", t: "mc", q: "Sob alagamento, o gás que fica preso nos tecidos e se acumula, disparando aerênquima e respostas de escape, é:",
      o: [["o etileno", true], ["o CO<sub>2</sub>", false], ["o oxigênio", false], ["o metano", false]],
      fb: "A difusão lenta na água retém o etileno produzido; ele estabiliza os ERF-VII e induz a lise de células corticais (aerênquima)." },
    { id: "10-11", t: "vf", q: "Em baixas doses controladas, espécies reativas de oxigênio (ROS) como o H<sub>2</sub>O<sub>2</sub> podem atuar como mensageiros que disparam respostas de defesa.",
      o: [["Verdadeiro", true], ["Falso", false]],
      fb: "Em excesso as ROS oxidam lipídios, proteínas e DNA; em dose baixa, o H<sub>2</sub>O<sub>2</sub> é um sinal. O sistema antioxidante mantém o equilíbrio." },
    { id: "10-12", t: "mc", q: "O aerênquima formado sob alagamento é:",
      o: [["um tecido com grandes espaços de ar que conduz O<sub>2</sub> da parte aérea até as raízes hipóxicas", true], ["uma camada de cera que impermeabiliza a raiz", false], ["um acúmulo de amido de reserva", false], ["um tipo de tricoma radicular", false]],
      fb: "Forma-se por morte programada de células do córtex; cria um canal aerífero contínuo que alivia a falta de O<sub>2</sub> na raiz." },
    { id: "10-13", t: "mc", q: "O \"priming\" (memória de estresse) refere-se ao fato de que plantas aclimatadas:",
      o: [["retêm parte da tolerância por dias a semanas após o estímulo cessar, via marcas epigenéticas e metabólitos persistentes", true], ["transmitem a tolerância a todas as gerações seguintes", false], ["ficam permanentemente estressadas", false], ["perdem a capacidade de responder a novos estresses", false]],
      fb: "É a base do endurecimento (\"hardening\") de mudas: um estímulo moderado prévio deixa a planta mais preparada para o próximo." }
  ]

};
